// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3gcLOHZtUkC9K8hJ14CO0ec4zhn0D6nE',
    appId: '1:14238624270:web:e062a7d92afa26802eea5f',
    messagingSenderId: '14238624270',
    projectId: 'chat-app-10fcd',
    authDomain: 'chat-app-10fcd.firebaseapp.com',
    storageBucket: 'chat-app-10fcd.firebasestorage.app',
    measurementId: 'G-78R589TZP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7BOOOCR4jc6SVLYHPXBOF4mQamYTfs00',
    appId: '1:14238624270:android:2c2133457c020a7e2eea5f',
    messagingSenderId: '14238624270',
    projectId: 'chat-app-10fcd',
    storageBucket: 'chat-app-10fcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC7stjneYNxXC70BGFbpF31q2vFKDL2zQ',
    appId: '1:14238624270:ios:ac1605aa6540afb82eea5f',
    messagingSenderId: '14238624270',
    projectId: 'chat-app-10fcd',
    storageBucket: 'chat-app-10fcd.firebasestorage.app',
    iosBundleId: 'com.example.newchatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC7stjneYNxXC70BGFbpF31q2vFKDL2zQ',
    appId: '1:14238624270:ios:ac1605aa6540afb82eea5f',
    messagingSenderId: '14238624270',
    projectId: 'chat-app-10fcd',
    storageBucket: 'chat-app-10fcd.firebasestorage.app',
    iosBundleId: 'com.example.newchatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3gcLOHZtUkC9K8hJ14CO0ec4zhn0D6nE',
    appId: '1:14238624270:web:b6bef9f7466dbfe42eea5f',
    messagingSenderId: '14238624270',
    projectId: 'chat-app-10fcd',
    authDomain: 'chat-app-10fcd.firebaseapp.com',
    storageBucket: 'chat-app-10fcd.firebasestorage.app',
    measurementId: 'G-Q19TY77DKQ',
  );
}
